version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-streetpong}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: streetpong-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - SKIP_TELEGRAM_SIGNATURE=${SKIP_TELEGRAM_SIGNATURE:-false}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - streetpong-network

  telegram-bot:
    image: streetpong-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: python app/telegram_bot.py
    networks:
      - streetpong-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - streetpong-network

  frontend:
    image: streetpong-frontend:latest
    restart: unless-stopped
    networks:
      - streetpong-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d streetpong.ru -d www.streetpong.ru

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:

networks:
  streetpong-network:
    driver: bridge 