"""add tables_count, net_type, has_roof to Location

Revision ID: e428b7530e05
Revises: 44918964e385
Create Date: 2025-06-14 19:18:58.803467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e428b7530e05'
down_revision = '44918964e385'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('tables_count', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('net_type', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('has_roof', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'has_roof')
    op.drop_column('locations', 'net_type')
    op.drop_column('locations', 'tables_count')
    # ### end Alembic commands ### 